version: '2'

services:

  todo:
    restart: always
    build: .
    volumes:
      - ./:/code
    tty: true
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/code
      - DATABASE_URL=postgresql://postgres:postgres@tododb:5432/postgres
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - tododb
    links:
      - tododb

  tododb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/data
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always

  tododbpgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ammarbanduk@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
       - pgadmin:/root/.pgadmin
    expose:
      - 80
    ports:
      - 5050:80    
    restart: always

volumes:
  postgres_data:
  pgadmin:
